version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    container_name: bot_db
    image: postgres
    restart: always
    volumes:
      - bot_db_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db 

volumes:
  bot_db_data:
